name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: Crear la imagen de docker
      run: docker build -t leonardo2552/lab-final:1.0 .
    - name: Imagen creada
      run: echo imagen creada
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test  
    - name: push a docker hub
      run: docker push leonardo2552/lab-final:1.0
    - name: Deploy al cluster k3d otro
      run: kubectl apply -f .\deployment.yaml